### ISSUE TITLE
Corescore leaderboard needed

### ISSUE THREAD

**Issue by rajesh-s** [olofk/corescore#5]
**Background**: Ran into this thought because I wanted to find out if someone has already run CoreScore on one of the FPGA boards that I wanted to try it on.

**Why**: 

- The intent is to capture available core count and other related statistics for the CoreScore project. 
- This could be useful to analyze cores vs specific hardware, core count over time or simply admire the glorious core numbers.
- It would also help compare obtained core count results with other's results (tool version differences etc.)
- Serve as a reference metric for future updates of the project or the core implementation.

**How**: Probably maintaining a continually updated list based on known CoreScore results would help.

Here's what I've collected so far.
https://gist.github.com/rajesh-s/15cee76a5696ef932e48e06e4aa88fe8

Thanks for reading, please let me know your thoughts on this!

**Comment by olofk** [comment]
Yes! A leaderboard would be great. I was thinking it might be possible to automate something by parsing the .core file with some JavaScript, but I have no idea where to even start, so a manual list is good for now. Would be great to also note the cost also, so that it's possible to calculate max Core/$.

It would be really cool if we could do something like what I did for my [SERV video](https://diode.zone/videos/watch/0230a518-e207-4cf6-b5e2-69cc09411013) (check around 6:50), but again, I don't really know how to do html/JS stuff properly.

I'll contribute to your list in the meantime

**Comment by rajesh-s** [comment]
Thanks for your feedback! 

The SERV video representation is a good idea. I'll try to see if I can add visualization, make it interactive (with filters, sort etc.) and add the cost to the existing table.

**Comment by rajesh-s** [comment]
This looks like a good way to do it

https://airtable.com/integrations/github#

@mattvenn did it here https://github.com/mattvenn/logLUTs! If this looks good, I will try to fit it with CoreScore

**Comment by olofk** [comment]
Done! You can find the results on https://corescore.store
